#!/usr/bin/python3
# Form implementation generated from reading ui file 'select_game.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_sel_game(object):
    def setupUi(self, sel_game):
        sel_game.setObjectName("sel_game")
        sel_game.resize(639, 450)
        sel_game.setWindowTitle("")
        self.sel_game_label = QtWidgets.QLabel(sel_game)
        self.sel_game_label.setGeometry(QtCore.QRect(0, 0, 631, 111))
        self.sel_game_label.setStyleSheet("font: 25 22pt \"Noto Sans\";")
        self.sel_game_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sel_game_label.setObjectName("sel_game_label")
        self.region_game = QtWidgets.QPushButton(sel_game)
        self.region_game.setGeometry(QtCore.QRect(130, 210, 131, 51))
        self.region_game.setObjectName("region_game")
        self.country_game = QtWidgets.QPushButton(sel_game)
        self.country_game.setGeometry(QtCore.QRect(380, 210, 131, 51))
        self.country_game.setObjectName("country_game")

        self.retranslateUi(sel_game)
        QtCore.QMetaObject.connectSlotsByName(sel_game)

    def retranslateUi(self, sel_game):
        _translate = QtCore.QCoreApplication.translate
        self.sel_game_label.setText(_translate("sel_game", "sel_game_label"))
        self.region_game.setText(_translate("sel_game", "region_game"))
        self.country_game.setText(_translate("sel_game", "country_game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sel_game = QtWidgets.QWidget()
    ui = Ui_sel_game()
    ui.setupUi(sel_game)
    sel_game.show()
    sys.exit(app.exec())
